import {useEffect,useState} from 'react';
import {LayoutDashboard,DoorOpen,Gauge,Receipt,Wrench,Users,ArrowUpRight,Plus,Check,LogOut,ShieldCheck} from 'lucide-react';
import {api,baht,monthLabel,thaiDate} from '../api';
import {Badge,Notice,Loading,Empty,Field,Modal} from '../components/UI';
const navigation=[['overview','ภาพรวม',LayoutDashboard],['rooms','ห้องพักและผู้พักอาศัย',DoorOpen],['meters','บันทึกมิเตอร์',Gauge],['invoices','ใบแจ้งหนี้และการชำระ',Receipt],['maintenance','รายการแจ้งซ่อม',Wrench]];
const categories={AC:'เครื่องปรับอากาศ',PLUMBING:'ประปา',ELECTRICAL:'ไฟฟ้า',FURNITURE:'เฟอร์นิเจอร์',OTHER:'อื่น ๆ'};
export default function AdminDashboard(){
 const [tab,setTab]=useState('overview'),[data,setData]=useState(null),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState(null),[selectedRoom,setSelectedRoom]=useState('2'),[billingMonth,setBillingMonth]=useState(''),[water,setWater]=useState(''),[electric,setElectric]=useState('');
 async function load(){const [o,r,u,b,m,t]=await Promise.all([api('/admin/overview'),api('/admin/rooms'),api('/admin/residents'),api('/invoices'),api('/meter-readings'),api('/maintenance')]);setData({overview:o,rooms:r.rooms,residents:u.residents,invoices:b.invoices,readings:m.readings,requests:t.requests});}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 const latest=data?.readings.find(m=>m.room_id===Number(selectedRoom));
 useEffect(()=>{if(latest){const d=new Date(latest.billing_month);d.setUTCMonth(d.getUTCMonth()+1);setBillingMonth(d.toISOString().slice(0,7));}else setBillingMonth(new Date().toISOString().slice(0,7));setWater('');setElectric('');},[selectedRoom,latest?.id]);
 async function mutate(path,method,body,message){setBusy(true);setError('');setSuccess('');try{await api(path,{method,body});await load();setSuccess(message);setModal(null);return true;}catch(e){setError(e.message);return false;}finally{setBusy(false);}}
 async function saveMeter(e){e.preventDefault();await mutate('/meter-readings','POST',{room_id:Number(selectedRoom),billing_month:billingMonth+'-01',prev_water_unit:Number(latest?.curr_water_unit||0),curr_water_unit:Number(water),prev_electric_unit:Number(latest?.curr_electric_unit||0),curr_electric_unit:Number(electric)},'บันทึกมิเตอร์แล้ว สามารถออกใบแจ้งหนี้จากตารางด้านล่าง');}
 if(!data)return <div className="container"><Notice error={error}/>{!error&&<Loading/>}</div>;
 const {overview,rooms,invoices,requests,readings,residents}=data;
 const occupancy=Math.round(overview.rooms.occupied/overview.rooms.total*100);
 const openRequests=requests.filter(r=>r.status!=='RESOLVED');
 function invoiceTable(list){return list.length?<div className="table-scroll"><table><thead><tr><th>ใบแจ้งหนี้ / รอบบิล</th><th>ห้อง</th><th>ยอดรวม</th><th>สถานะ</th><th>ดำเนินการ</th></tr></thead><tbody>{list.map(i=><tr key={i.id}><td><strong>{i.invoice_number}</strong><small>{monthLabel(i.billing_cycle)}</small></td><td>{i.room_number}</td><td>{baht(i.total_amount)}</td><td><Badge status={i.payment_notification_status==='SUBMITTED'?'SUBMITTED':i.display_status}/></td><td><button className="text-button" onClick={()=>{setModal({type:'invoice',invoice:i});setError('');}}>รายละเอียด <ArrowUpRight size={14}/></button></td></tr>)}</tbody></table></div>:<Empty>ไม่มีรายการใบแจ้งหนี้</Empty>;}
 return <div className="admin-shell"><aside className="admin-sidebar"><div className="admin-label"><ShieldCheck size={21}/><div><strong>จัดการหอพัก</strong><small>ADMIN WORKSPACE</small></div></div><nav aria-label="เมนูผู้ดูแล">{navigation.map(([k,title,Icon])=><button key={k} className={tab===k?'selected':''} onClick={()=>{setTab(k);setError('');setSuccess('');}}><Icon size={19}/>{title}{k==='maintenance'&&openRequests.length>0&&<span>{openRequests.length}</span>}</button>)}</nav><div className="sidebar-occupancy"><span>อัตราการเข้าพัก</span><strong>{occupancy}<small>%</small></strong><div className="progress-track"><i style={{width:occupancy+'%'}}/></div><p>{overview.rooms.occupied} จาก {overview.rooms.total} ห้อง</p></div></aside><div className="admin-content"><div className="portal-heading"><div><span className="eyebrow">DATAF MANAGEMENT</span><h1>{navigation.find(n=>n[0]===tab)[1]}</h1><p>อาคาร A · โซนหอพัก CDTI</p></div><span className="date-chip">{thaiDate(new Date())}</span></div><Notice error={error} success={success}/>
 {tab==='overview'&&<><div className="kpi-grid">{[[DoorOpen,'ห้องว่างพร้อมเข้าพัก',overview.rooms.available,'จากทั้งหมด '+overview.rooms.total+' ห้อง','blue'],[Users,'ผู้พักอาศัยปัจจุบัน',overview.rooms.occupied,'อัตราเข้าพัก '+occupancy+'%','navy'],[Receipt,'ยอดค้างชำระทั้งหมด',baht(overview.billing.outstanding),'รอตรวจสอบ '+overview.billing.payment_reviews+' รายการ','orange'],[Wrench,'งานซ่อมที่ยังไม่เสร็จ',overview.maintenance.open,'รายการที่ต้องติดตาม','green']].map(([Icon,title,value,caption,color])=><article className="kpi-card" key={title}><div><span className={'kpi-icon '+color}><Icon size={21}/></span><span>{title}</span></div><strong>{value}</strong><p>{caption}</p></article>)}</div><section className="panel"><div className="panel-heading"><div><h2>สถานะห้องพัก</h2><p className="muted">ภาพรวมการจัดสรรห้องทั้ง 3 ชั้น</p></div><button className="text-button" onClick={()=>setTab('rooms')}>จัดการห้องพัก <ArrowUpRight size={16}/></button></div><div className="floor-map">{[1,2,3].map(f=><div className="floor-row" key={f}><span>ชั้น {f}</span><div>{rooms.filter(r=>r.floor===f).map(r=><button key={r.id} className={'room-cell '+r.occupancy_status.toLowerCase()} onClick={()=>{setTab('rooms');}} title={'ห้อง '+r.room_number}><DoorOpen size={16}/><strong>{r.room_number}</strong><small>{r.bed_type==='SINGLE'?'เตียงเดี่ยว':'เตียงคู่'}</small></button>)}</div></div>)}</div><div className="map-legend"><span><i className="vacant"/>ว่าง</span><span><i className="occupied"/>มีผู้พักอาศัย</span><span><i className="maintenance"/>ปรับปรุง</span></div></section><section className="panel"><div className="panel-heading"><h2>รายการรอตรวจสอบการชำระเงิน</h2><button className="text-button" onClick={()=>setTab('invoices')}>ดูใบแจ้งหนี้ทั้งหมด <ArrowUpRight size={16}/></button></div>{invoiceTable(invoices.filter(i=>i.payment_notification_status==='SUBMITTED'))}</section></>}
 {tab==='rooms'&&<section className="panel"><div className="panel-heading"><h2>ห้องพักทั้งหมด</h2><span className="count-tag">{rooms.length} ห้อง</span></div><div className="table-scroll"><table><thead><tr><th>ห้อง / ชั้น</th><th>ประเภท</th><th>ผู้พักอาศัย</th><th>ค่าเช่า / เดือน</th><th>สถานะ</th><th>จัดการ</th></tr></thead><tbody>{rooms.map(r=><tr key={r.id}><td><strong>{r.room_number}</strong><small>ชั้น {r.floor}</small></td><td>{r.room_type}</td><td>{r.resident_name||'—'}</td><td>{baht(r.rent_rate)}</td><td><Badge status={r.occupancy_status}/></td><td>{r.lease_id?<button className="text-button" onClick={()=>setModal({type:'end',room:r})}>สิ้นสุดสัญญา</button>:<div className="row-actions">{r.occupancy_status==='VACANT'&&<button className="text-button" onClick={()=>setModal({type:'assign',room:r})}><Plus size={15}/>จัดสรร</button>}<button className="text-button" disabled={busy} onClick={()=>mutate('/rooms/'+r.id+'/status','PATCH',{status:r.occupancy_status==='MAINTENANCE'?'VACANT':'MAINTENANCE'},'อัปเดตสถานะห้องแล้ว')}>{r.occupancy_status==='MAINTENANCE'?'เปิดห้อง':'ปรับปรุง'}</button></div>}</td></tr>)}</tbody></table></div></section>}
 {tab==='meters'&&<><section className="panel"><div className="panel-heading"><div><h2>บันทึกการใช้สาธารณูปโภค</h2><p className="muted">ค่าน้ำ 18 บาท / หน่วย · ค่าไฟ 8 บาท / หน่วย</p></div><Gauge size={26}/></div><form className="meter-form" onSubmit={saveMeter}><Field label="ห้องพัก"><select value={selectedRoom} onChange={e=>setSelectedRoom(e.target.value)}>{rooms.map(r=><option key={r.id} value={r.id}>ห้อง {r.room_number} · {r.resident_name||'ไม่มีผู้พักอาศัย'}</option>)}</select></Field><Field label="รอบบิล"><input type="month" required value={billingMonth} onChange={e=>setBillingMonth(e.target.value)}/></Field><Field label="มิเตอร์น้ำครั้งก่อน"><input type="number" value={latest?.curr_water_unit||0} disabled/></Field><Field label="มิเตอร์น้ำปัจจุบัน"><input type="number" min={latest?.curr_water_unit||0} max={99999999} step="0.01" required value={water} onChange={e=>setWater(e.target.value)}/></Field><Field label="มิเตอร์ไฟครั้งก่อน"><input type="number" value={latest?.curr_electric_unit||0} disabled/></Field><Field label="มิเตอร์ไฟปัจจุบัน"><input type="number" min={latest?.curr_electric_unit||0} max={99999999} step="0.01" required value={electric} onChange={e=>setElectric(e.target.value)}/></Field><div className="meter-form-action"><button className="button primary" disabled={busy}><Plus size={18}/>{busy?'กำลังบันทึก…':'บันทึกมิเตอร์'}</button></div></form></section><section className="panel"><div className="panel-heading"><h2>ประวัติมิเตอร์และการออกบิล</h2></div><div className="table-scroll"><table><thead><tr><th>ห้อง</th><th>รอบบิล</th><th>น้ำ (ก่อน → ปัจจุบัน)</th><th>ไฟ (ก่อน → ปัจจุบัน)</th><th>ใบแจ้งหนี้</th></tr></thead><tbody>{readings.map(m=><tr key={m.id}><td>{m.room_number}</td><td>{monthLabel(m.billing_month)}</td><td>{m.prev_water_unit} → {m.curr_water_unit}</td><td>{m.prev_electric_unit} → {m.curr_electric_unit}</td><td>{invoices.some(i=>i.meter_reading_id===m.id)?<span className="green inline-icon"><Check size={15}/>ออกบิลแล้ว</span>:<button className="text-button" disabled={busy} onClick={()=>mutate('/invoices/generate','POST',{room_id:m.room_id,billing_cycle:m.billing_month},'ออกใบแจ้งหนี้เรียบร้อยแล้ว')}>ออกใบแจ้งหนี้</button>}</td></tr>)}</tbody></table></div></section></>}
 {tab==='invoices'&&<><div className="billing-summary"><span>ยอดรับชำระแล้ว <strong className="green">{baht(overview.billing.collected)}</strong></span><span>ยอดค้างทั้งหมด <strong>{baht(overview.billing.outstanding)}</strong></span><span>รอตรวจสอบ <strong>{overview.billing.payment_reviews} รายการ</strong></span></div><section className="panel"><div className="panel-heading"><h2>ใบแจ้งหนี้ทั้งหมด</h2><span className="count-tag">{invoices.length} รายการ</span></div>{invoiceTable(invoices)}</section></>}
 {tab==='maintenance'&&<section className="panel"><div className="panel-heading"><h2>รายการแจ้งซ่อม</h2><span className="count-tag">{requests.length} รายการ</span></div>{requests.length===0?<Empty>ยังไม่มีรายการแจ้งซ่อมจากผู้พักอาศัย</Empty>:<div className="admin-tickets">{requests.map(r=><article className="admin-ticket" key={r.id}><div><span className="room-type">#{r.id} · ห้อง {r.room_number}</span><h3>{categories[r.category]}</h3><p>{r.description}</p><small>{thaiDate(r.created_at)}</small></div><label className="field"><span>สถานะงาน</span><select aria-label={'สถานะงาน #'+r.id} disabled={busy} value={r.status} onChange={e=>mutate('/maintenance/'+r.id,'PATCH',{status:e.target.value},'อัปเดตสถานะงานซ่อมแล้ว')}><option value="REPORTED">รับเรื่องแล้ว</option><option value="IN_PROGRESS">กำลังดำเนินการ</option><option value="RESOLVED">เรียบร้อยแล้ว</option></select></label></article>)}</div>}</section>}
 </div>{modal&&<Modal title={modal.type==='invoice'?'รายละเอียดใบแจ้งหนี้':modal.type==='end'?'สิ้นสุดสัญญาห้อง '+modal.room.room_number:'จัดสรรห้อง '+modal.room.room_number} onClose={()=>{if(!busy){setModal(null);setError('');}}}><div className="modal-form"><Notice error={error}/>{modal.type==='invoice'?<><p><strong>{modal.invoice.invoice_number}</strong> · ห้อง {modal.invoice.room_number}</p><div className="cost-breakdown">{[['ค่าเช่า',modal.invoice.rent_amount],['ค่าน้ำ',modal.invoice.water_amount],['ค่าไฟ',modal.invoice.electric_amount],['รวม',modal.invoice.total_amount]].map(([label,amount])=><div key={label}><span>{label}</span><strong>{baht(amount)}</strong></div>)}</div><Badge status={modal.invoice.display_status}/>{modal.invoice.payment_notification_status==='SUBMITTED'&&<><p className="payment-note">ข้อความผู้พักอาศัย: {modal.invoice.payment_note||'ไม่ได้ระบุข้อความ'}</p><p className="muted">ตรวจสอบยอดรับชำระจริงก่อนยืนยัน</p><div className="modal-actions"><button className="button secondary" disabled={busy} onClick={()=>mutate('/invoices/'+modal.invoice.id+'/payment-review','POST',{decision:'REJECTED'},'ส่งคืนการแจ้งชำระแล้ว')}>ส่งคืนให้แจ้งใหม่</button><button className="button primary" disabled={busy} onClick={()=>mutate('/invoices/'+modal.invoice.id+'/payment-review','POST',{decision:'APPROVED'},'ยืนยันรับชำระเงินแล้ว')}><Check size={17}/>ยืนยันรับชำระ</button></div></>}</>:modal.type==='end'?<><p>สิ้นสุดสัญญาของ {modal.room.resident_name} ห้อง {modal.room.room_number} และเปิดห้องให้จัดสรรใหม่</p><p className="muted">ประวัติใบแจ้งหนี้และการชำระเงินยังคงอยู่</p><button className="button primary full" disabled={busy} onClick={()=>mutate('/leases/'+modal.room.lease_id+'/end','POST',{},'สิ้นสุดสัญญาแล้ว')}><LogOut size={18}/>ยืนยันสิ้นสุดสัญญา</button></>:residents.filter(r=>!r.room_id).length===0?<Empty>ผู้พักอาศัยทุกบัญชีมีห้องแล้ว<br/>กรุณาสิ้นสุดสัญญาเดิมก่อนย้ายห้อง</Empty>:<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);mutate('/rooms/'+modal.room.id+'/lease','POST',{resident_id:f.get('resident_id'),start_date:f.get('start_date'),end_date:f.get('end_date'),deposit_paid:Number(f.get('deposit_paid'))},'จัดสรรห้องพักแล้ว');}}><Field label="ผู้พักอาศัย"><select name="resident_id" required>{residents.filter(r=>!r.room_id).map(r=><option value={r.id} key={r.id}>{r.full_name_th}</option>)}</select></Field><Field label="วันเริ่มสัญญา"><input type="date" name="start_date" required/></Field><Field label="วันสิ้นสุดสัญญา"><input type="date" name="end_date" required/></Field><Field label="เงินประกันที่รับแล้ว"><input type="number" name="deposit_paid" min="0" step="0.01" defaultValue={modal.room.deposit_amount} required/></Field><button className="button primary full" disabled={busy}>ยืนยันจัดสรรห้อง</button></form>}</div></Modal>}</div>;
}

