import {useState} from 'react';
import {Navigate,useNavigate} from 'react-router-dom';
import {ArrowRight,ShieldCheck,Eye,EyeOff,Building2} from 'lucide-react';
import {useAuth} from '../auth';
import {Notice,Field,Loading} from '../components/UI';
export default function LoginPage(){
 const {user,login,loading}=useAuth(),navigate=useNavigate(),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[visible,setVisible]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 if(loading)return <Loading/>;if(user)return <Navigate to={user.role==='SUPER_ADMIN'?'/admin':'/resident'} replace/>;
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{navigate(await login(email.trim(),password),{replace:true});}catch(err){setError(err.message);}finally{setBusy(false);}}
 return <div className="login-page container"><div className="login-story"><span className="eyebrow">WELCOME HOME</span><h1>เรื่องของหอพัก<br/>จัดการได้ในที่เดียว<span>.</span></h1><p>ตรวจสอบบิล แจ้งซ่อม และติดต่อผู้ดูแล<br/>พร้อมให้คุณใช้เวลาเต็มที่กับชีวิตนักศึกษา</p><div className="login-illustration"><img src="/logo.png" alt="DataF Student Dormitory Management System"/></div><span className="login-story-note"><Building2 size={18}/> DataF · Student Living</span></div><section className="login-form-panel"><div className="login-icon"><ShieldCheck size={25}/></div><h2>ยินดีต้อนรับกลับ</h2><p className="muted">เข้าสู่ระบบด้วยบัญชีที่ได้รับจากหอพัก</p><form onSubmit={submit}><Notice error={error}/><Field label="อีเมลมหาวิทยาลัย"><input type="email" autoComplete="username" placeholder="รหัสนักศึกษา@cdti.ac.th" required maxLength={255} value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field label="รหัสผ่าน"><div className="password-input"><input type={visible?'text':'password'} autoComplete="current-password" required maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" className="icon-button" aria-label={visible?'ซ่อนรหัสผ่าน':'แสดงรหัสผ่าน'} onClick={()=>setVisible(!visible)}>{visible?<EyeOff size={19}/>:<Eye size={19}/>}</button></div></Field><button className="button primary full" disabled={busy}>{busy?'กำลังเข้าสู่ระบบ…':'เข้าสู่ระบบ'}<ArrowRight size={19}/></button></form><div className="login-help"><ShieldCheck size={18}/><span>ระบบจะเปิดหน้าบริการตามสิทธิ์ของบัญชี<br/>หากเข้าใช้งานไม่ได้ กรุณาติดต่อผู้ดูแลหอพัก</span></div></section></div>;
}
