import {useEffect,useState} from 'react';
import {Receipt, Wrench, Contact, BookOpen, ArrowUpRight, CalendarDays, Home, Droplets, Zap, Building2, Phone, Clock, Send, CheckCircle2} from 'lucide-react';
import {useAuth} from '../auth';
import {api,baht,thaiDate,monthLabel} from '../api';
import {Badge,Notice,Loading,Empty,Field,Modal} from '../components/UI';
const actions=[['bills','บริการชำระบิล','ตรวจสอบค่าใช้จ่ายและแจ้งชำระ',Receipt],['maintenance','บริการแจ้งซ่อม','แจ้งปัญหาและติดตามสถานะ',Wrench],['staff','บริการติดต่อผู้ดูแลหอพัก','ทีมดูแลพร้อมให้ความช่วยเหลือ',Contact],['rules','บริการข้อมูลกฎระเบียบหอพัก','กติกาการอยู่ร่วมกัน',BookOpen]];
const categories={AC:'เครื่องปรับอากาศ',PLUMBING:'ประปา / ห้องน้ำ',ELECTRICAL:'ระบบไฟฟ้า',FURNITURE:'เฟอร์นิเจอร์',OTHER:'อื่น ๆ'};
const staffRoles={MANAGER:'ผู้จัดการหอพัก',MAID:'แม่บ้าน',SECURITY:'เจ้าหน้าที่รักษาความปลอดภัย',TECHNICIAN:'ช่างซ่อมบำรุง'};
export default function ResidentPortal(){
 const {user,room}=useAuth(),[tab,setTab]=useState('bills'),[data,setData]=useState(null),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false),[invoiceId,setInvoiceId]=useState(''),[payment,setPayment]=useState(false),[note,setNote]=useState(''),[category,setCategory]=useState('AC'),[description,setDescription]=useState('');
 async function load(){const [b,m,s,r]=await Promise.all([api('/invoices'),api('/maintenance'),api('/staff'),api('/regulations')]);setData({invoices:b.invoices,requests:m.requests,staff:s.staff,rules:r.regulations});}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 const invoice=data?.invoices.find(i=>i.id===invoiceId)||data?.invoices[0];
 async function notifyPayment(e){e.preventDefault();setBusy(true);setError('');try{await api('/invoices/'+invoice.id+'/payment-notification',{method:'POST',body:{note}});await load();setPayment(false);setNote('');setSuccess('ส่งแจ้งชำระเงินแล้ว ผู้ดูแลจะตรวจสอบและอัปเดตสถานะให้คุณ');}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function submitRepair(e){e.preventDefault();setBusy(true);setError('');setSuccess('');try{await api('/maintenance',{method:'POST',body:{category,description}});await load();setDescription('');setSuccess('ส่งคำขอแจ้งซ่อมแล้ว คุณติดตามสถานะได้ด้านล่าง');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <div className="portal-page container"><div className="portal-heading"><div><div className="eyebrow">RESIDENT SERVICES</div><h1>สวัสดี, {user.full_name_th.split(' ')[0]} <span className="wave">☀</span></h1><p>ยินดีต้อนรับสู่พื้นที่บริการของคุณ</p></div><div className="resident-room"><Home size={22}/><div><strong>{room?'ห้อง '+room.room_number:'ยังไม่ได้จัดสรรห้อง'}</strong><span>{room?room.building+' · ชั้น '+room.floor:'ติดต่อผู้ดูแลเพื่อจัดสรรห้องพัก'}</span></div></div></div><div className="action-grid" role="tablist" aria-label="บริการผู้พักอาศัย">{actions.map(([key,title,subtitle,Icon],i)=><button key={key} className={'action-card '+(tab===key?'selected':'')} role="tab" aria-selected={tab===key} aria-controls={'service-'+key} id={'tab-'+key} onClick={()=>{setTab(key);setError('');setSuccess('');}}><div className="action-icon"><Icon size={24}/><span>0{i+1}</span></div><h2>{title}</h2><p>{subtitle}</p><ArrowUpRight className="action-arrow" size={19}/></button>)}</div><Notice error={error} success={success}/>{!data&&!error?<Loading/>:data&&<div role="tabpanel" id={'service-'+tab} aria-labelledby={'tab-'+tab}>
 {tab==='bills'&&<div className="resident-bills"><section className="panel invoice-panel"><div className="panel-heading"><div><span className="eyebrow">MONTHLY STATEMENT</span><h2>ใบแจ้งค่าใช้จ่าย</h2></div>{invoice&&<Badge status={invoice.payment_notification_status==='SUBMITTED'?'SUBMITTED':invoice.display_status}/>}</div>{!invoice?<Empty>ยังไม่มีใบแจ้งหนี้สำหรับบัญชีนี้</Empty>:<><div className="invoice-month"><div><CalendarDays size={18}/><select aria-label="รอบบิล" value={invoice.id} onChange={e=>setInvoiceId(e.target.value)}>{data.invoices.map(i=><option value={i.id} key={i.id}>{monthLabel(i.billing_cycle)}</option>)}</select></div><span>{invoice.invoice_number}</span></div><div className="invoice-lines">{[[Home,'ค่าเช่าห้องพัก','ห้อง '+invoice.room_number,invoice.rent_amount],[Droplets,'ค่าน้ำประปา',`${Number(invoice.curr_water_unit)-Number(invoice.prev_water_unit)} หน่วย × ${baht(invoice.water_rate_per_unit)}`,invoice.water_amount],[Zap,'ค่าไฟฟ้า',`${Number(invoice.curr_electric_unit)-Number(invoice.prev_electric_unit)} หน่วย × ${baht(invoice.electric_rate_per_unit)}`,invoice.electric_amount]].map(([Icon,label,sub,amount])=><div className="invoice-line" key={label}><span className="line-icon"><Icon size={20}/></span><div><strong>{label}</strong><small>{sub}</small></div><b>{baht(amount)}</b></div>)}</div><div className="invoice-total"><span>ยอดรวมที่ต้องชำระ</span><strong>{baht(invoice.total_amount)}</strong></div><div className="invoice-due"><CalendarDays size={16}/>กำหนดชำระ {thaiDate(invoice.due_date)}</div>{invoice.status==='PAID'?<div className="paid-confirmation"><CheckCircle2 size={20}/>ผู้ดูแลยืนยันการชำระเงินแล้ว</div>:<button className="button primary full" disabled={invoice.payment_notification_status==='SUBMITTED'} onClick={()=>{setPayment(true);setError('');}}><Receipt size={18}/>{invoice.payment_notification_status==='SUBMITTED'?'แจ้งแล้ว · รอผู้ดูแลตรวจสอบ':'คลิกเพื่อแจ้งชำระเงิน (Manual)'}</button>}</>}</section><aside className="bill-guidance"><div className="navy-panel"><Receipt size={28}/><h2>ชำระครบ<br/>พักได้สบายใจ</h2><p>ชำระค่าใช้จ่ายวันที่ 1–5 ของทุกเดือน แล้วกดแจ้งชำระเงินเพื่อให้ผู้ดูแลตรวจสอบ</p><span>แจ้งชำระ ≠ ยืนยันยอดชำระ</span></div><div className="panel compact"><h3><Clock size={18}/> ข้อมูลการชำระเงิน</h3><p>ติดต่อผู้ดูแลเพื่อยืนยันช่องทางชำระเงิน เมื่อชำระแล้วสามารถระบุวัน เวลา หรือข้อมูลอ้างอิงในข้อความแจ้งชำระได้</p><button className="text-button" onClick={()=>setTab('staff')}>ติดต่อผู้ดูแล <ArrowUpRight size={15}/></button></div></aside></div>}
 {tab==='maintenance'&&<div className="service-columns"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">WE'RE HERE TO HELP</span><h2>แจ้งปัญหาภายในห้องพัก</h2></div><Wrench size={25}/></div><form onSubmit={submitRepair} className="service-form"><Field label="หมายเลขห้อง"><input value={room?.room_number||'ยังไม่มีห้องพัก'} disabled/></Field><Field label="หมวดหมู่ปัญหา"><select value={category} onChange={e=>setCategory(e.target.value)}>{Object.entries(categories).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><Field label="รายละเอียดปัญหา" hint="ระบุตำแหน่งและอาการของปัญหา 10–2,000 ตัวอักษร"><textarea placeholder="เช่น เครื่องปรับอากาศมีน้ำหยดบริเวณโต๊ะอ่านหนังสือ…" required minLength={10} maxLength={2000} rows={5} value={description} onChange={e=>setDescription(e.target.value)}/></Field><button className="button primary full" disabled={busy||!room}><Send size={17}/>{busy?'กำลังส่ง…':'ส่งเรื่องแจ้งซ่อม'}</button></form></section><section className="panel"><div className="panel-heading"><h2>ติดตามรายการแจ้งซ่อม</h2><span className="count-tag">{data.requests.length}</span></div>{data.requests.length===0?<Empty>ยังไม่มีรายการแจ้งซ่อม<br/>เมื่อส่งเรื่องแล้ว สถานะจะแสดงที่นี่</Empty>:<div className="ticket-list">{data.requests.map(r=><article className="ticket" key={r.id}><div><strong>#{r.id} · {categories[r.category]}</strong><Badge status={r.status}/></div><p>{r.description}</p><small>{thaiDate(r.created_at)} · ห้อง {r.room_number}</small></article>)}</div>}</section></div>}
 {tab==='staff'&&<section className="panel staff-panel"><div className="panel-heading"><div><span className="eyebrow">YOUR DORM TEAM</span><h2>ผู้ดูแลใกล้ตัวคุณ</h2><p className="muted">ติดต่อทีมงานตามเวลาปฏิบัติงาน</p></div><Contact size={28}/></div><div className="staff-grid">{data.staff.map(s=><article className="staff-card" key={s.id}><div className="staff-avatar">{s.name.slice(0,1)}</div><div><span className="room-type">{staffRoles[s.role]}</span><h3>{s.name}</h3></div>{s.is_emergency&&<span className="emergency-tag">ติดต่อฉุกเฉิน</span>}<p><Clock size={16}/>{s.shift_schedule}</p><a className="phone-link" href={'tel:'+s.phone_number}><Phone size={17}/>{s.phone_number.replace(/(\d{3})(\d{3})(\d{4})/,'$1-$2-$3')}<ArrowUpRight size={16}/></a></article>)}</div></section>}
 {tab==='rules'&&<section className="panel regulations-panel"><div className="panel-heading"><div><span className="eyebrow">LIVING WELL, TOGETHER</span><h2>กฎระเบียบหอพัก</h2><p className="muted">มีผลตั้งแต่ 1 สิงหาคม 2026 · คณะกรรมการนิติบุคคลและฝ่ายจัดการหอพัก</p></div><BookOpen size={28}/></div><div className="regulation-list">{data.rules.map((r,i)=><article key={r.id}><span className="rule-number">0{i+1}</span><div><h3>{r.rule_title}</h3><p>{r.rule_content}</p><span className="rule-penalty">{r.penalty_details}</span></div></article>)}</div></section>}
 </div>}{payment&&invoice&&<Modal title="แจ้งชำระเงิน" onClose={()=>{if(!busy)setPayment(false);}}><form className="modal-form" onSubmit={notifyPayment}><p>ใบแจ้งหนี้ {invoice.invoice_number}<br/><strong>{baht(invoice.total_amount)}</strong></p><Notice error={error}/><Field label="ข้อความถึงผู้ดูแล (ไม่บังคับ)" hint="เช่น วันที่ เวลา และข้อมูลอ้างอิงการชำระเงิน"><textarea rows={4} maxLength={500} value={note} onChange={e=>setNote(e.target.value)}/></Field><p className="muted">สถานะจะเป็น “รอตรวจสอบ” จนกว่าผู้ดูแลจะยืนยันยอดชำระ</p><button className="button primary full" disabled={busy}>{busy?'กำลังส่ง…':'ยืนยันการแจ้งชำระเงิน'}</button></form></Modal>}</div>;
}

