-- DataF demo seed; PostgreSQL 16. Safe to rerun: existing records are preserved.
BEGIN;
-- DataF PostgreSQL 16 schema. Additive and non-destructive; applied by seed.sql.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
DO $$ BEGIN CREATE TYPE user_role AS ENUM ('SUPER_ADMIN','STUDENT_RESIDENT'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE room_status AS ENUM ('VACANT','MAINTENANCE'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE invoice_status AS ENUM ('PENDING','PAID','OVERDUE'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE maintenance_status AS ENUM ('REPORTED','IN_PROGRESS','RESOLVED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE staff_role AS ENUM ('MANAGER','MAID','SECURITY','TECHNICIAN'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE TABLE IF NOT EXISTS users (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), student_id varchar(20) UNIQUE NOT NULL,
 full_name_th varchar(150) NOT NULL, full_name_en varchar(150) NOT NULL,
 email varchar(255) UNIQUE NOT NULL CHECK (email = lower(email)), password_hash varchar(255) NOT NULL,
 phone_number varchar(50), role user_role NOT NULL DEFAULT 'STUDENT_RESIDENT', created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS room_types (
 id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(100) UNIQUE NOT NULL,
 bed_type varchar(10) UNIQUE NOT NULL CHECK (bed_type IN ('SINGLE','TWIN')),
 base_rent numeric(10,2) NOT NULL CHECK (base_rent >= 0), deposit_amount numeric(10,2) NOT NULL CHECK (deposit_amount >= 0),
 advance_payment numeric(10,2) NOT NULL CHECK (advance_payment >= 0), area_sqm int NOT NULL,
 description text, amenities jsonb NOT NULL DEFAULT '[]'
);
CREATE TABLE IF NOT EXISTS rooms (
 id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, room_number varchar(20) UNIQUE NOT NULL,
 floor int NOT NULL CHECK (floor BETWEEN 1 AND 3), building varchar(50) NOT NULL DEFAULT 'อาคาร A',
 campus_zone varchar(50) NOT NULL DEFAULT 'โซนหอพัก CDTI', room_type_id int NOT NULL REFERENCES room_types(id),
 status room_status NOT NULL DEFAULT 'VACANT', rent_rate numeric(10,2) NOT NULL CHECK (rent_rate >= 0)
);
CREATE TABLE IF NOT EXISTS room_images (
 room_id int PRIMARY KEY REFERENCES rooms(id), asset_path text UNIQUE NOT NULL, alt_text text NOT NULL
);
CREATE TABLE IF NOT EXISTS leases (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), room_id int NOT NULL REFERENCES rooms(id), resident_id uuid NOT NULL REFERENCES users(id),
 start_date date NOT NULL, end_date date NOT NULL CHECK (end_date > start_date),
 deposit_paid numeric(10,2) NOT NULL CHECK (deposit_paid >= 0), contract_active boolean NOT NULL DEFAULT true,
 created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS one_active_lease_per_room ON leases(room_id) WHERE contract_active;
CREATE UNIQUE INDEX IF NOT EXISTS one_active_lease_per_resident ON leases(resident_id) WHERE contract_active;
CREATE TABLE IF NOT EXISTS utility_rates (
 id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, effective_date date UNIQUE NOT NULL,
 water_rate_per_unit numeric(8,2) NOT NULL DEFAULT 18 CHECK (water_rate_per_unit >= 0),
 electric_rate_per_unit numeric(8,2) NOT NULL DEFAULT 8 CHECK (electric_rate_per_unit >= 0),
 is_active boolean NOT NULL DEFAULT true
);
CREATE UNIQUE INDEX IF NOT EXISTS one_active_rate ON utility_rates(is_active) WHERE is_active;
CREATE TABLE IF NOT EXISTS meter_readings (
 id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, room_id int NOT NULL REFERENCES rooms(id),
 billing_month date NOT NULL CHECK (extract(day from billing_month) = 1),
 prev_water_unit numeric(10,2) NOT NULL CHECK (prev_water_unit >= 0), curr_water_unit numeric(10,2) NOT NULL CHECK (curr_water_unit >= prev_water_unit),
 prev_electric_unit numeric(10,2) NOT NULL CHECK (prev_electric_unit >= 0), curr_electric_unit numeric(10,2) NOT NULL CHECK (curr_electric_unit >= prev_electric_unit),
 created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (room_id,billing_month)
);
CREATE TABLE IF NOT EXISTS invoices (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), invoice_number varchar(50) UNIQUE NOT NULL,
 room_id int NOT NULL REFERENCES rooms(id), resident_id uuid NOT NULL REFERENCES users(id),
 meter_reading_id int NOT NULL UNIQUE REFERENCES meter_readings(id), utility_rate_id int NOT NULL REFERENCES utility_rates(id),
 billing_cycle date NOT NULL CHECK (extract(day from billing_cycle) = 1),
 rent_amount numeric(10,2) NOT NULL CHECK (rent_amount >= 0), water_amount numeric(10,2) NOT NULL CHECK (water_amount >= 0),
 electric_amount numeric(10,2) NOT NULL CHECK (electric_amount >= 0),
 total_amount numeric(10,2) GENERATED ALWAYS AS (rent_amount + water_amount + electric_amount) STORED,
 status invoice_status NOT NULL DEFAULT 'PENDING', due_date date NOT NULL,
 paid_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (room_id,billing_cycle),
 CHECK (due_date >= billing_cycle), CHECK ((status = 'PAID') = (paid_at IS NOT NULL))
);
CREATE TABLE IF NOT EXISTS payment_notifications (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), invoice_id uuid NOT NULL REFERENCES invoices(id),
 resident_id uuid NOT NULL REFERENCES users(id), note varchar(500) NOT NULL DEFAULT '',
 status varchar(12) NOT NULL DEFAULT 'SUBMITTED' CHECK (status IN ('SUBMITTED','APPROVED','REJECTED')),
 created_at timestamptz NOT NULL DEFAULT now(), reviewed_by uuid REFERENCES users(id), reviewed_at timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS one_pending_payment_notice ON payment_notifications(invoice_id) WHERE status = 'SUBMITTED';
CREATE TABLE IF NOT EXISTS maintenance_requests (
 id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, room_id int NOT NULL REFERENCES rooms(id), resident_id uuid NOT NULL REFERENCES users(id),
 category varchar(100) NOT NULL CHECK (category IN ('AC','PLUMBING','ELECTRICAL','FURNITURE','OTHER')),
 description text NOT NULL CHECK (char_length(description) BETWEEN 10 AND 2000), status maintenance_status NOT NULL DEFAULT 'REPORTED',
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS staff_directory (
 id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(150) UNIQUE NOT NULL, role staff_role NOT NULL,
 age int CHECK (age BETWEEN 18 AND 100), shift_schedule varchar(255) NOT NULL, phone_number varchar(50) NOT NULL,
 is_emergency boolean NOT NULL DEFAULT false
);
CREATE TABLE IF NOT EXISTS dorm_regulations (
 id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, category varchar(100) UNIQUE NOT NULL, rule_title varchar(255) NOT NULL,
 rule_content text NOT NULL, penalty_details text, effective_date date NOT NULL DEFAULT '2026-08-01'
);
CREATE TABLE IF NOT EXISTS auth_sessions (
 id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), expires_at timestamptz NOT NULL,
 revoked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS auth_sessions_user_idx ON auth_sessions(user_id);
CREATE INDEX IF NOT EXISTS invoices_resident_idx ON invoices(resident_id,billing_cycle DESC);
CREATE INDEX IF NOT EXISTS maintenance_resident_idx ON maintenance_requests(resident_id,created_at DESC);
CREATE TABLE IF NOT EXISTS audit_events (
 id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, actor_id uuid REFERENCES users(id), action varchar(80) NOT NULL,
 entity_id text NOT NULL, details jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now()
);
-- Occupancy has one source of truth: an active lease. No duplicated tenant pointer.
CREATE OR REPLACE VIEW room_inventory AS
 SELECT r.*, t.name AS room_type, t.bed_type, t.area_sqm, t.amenities, t.description,
 t.deposit_amount, t.advance_payment,
 CASE WHEN l.id IS NOT NULL THEN 'OCCUPIED' ELSE r.status::text END AS occupancy_status,
 l.resident_id AS current_resident_id, l.id AS lease_id, i.asset_path AS image_url, i.alt_text
 FROM rooms r JOIN room_types t ON t.id = r.room_type_id
 LEFT JOIN leases l ON l.room_id = r.id AND l.contract_active
 LEFT JOIN room_images i ON i.room_id = r.id;

INSERT INTO users(student_id,full_name_th,full_name_en,phone_number,email,password_hash,role) VALUES ('6810301018','นายเกียรติศักดิ์ ปรีชานนท์','Kiadtisak Preechanon','0957506052','6810301018@cdti.ac.th','$2b$12$bI7aQKjc1fGw8hi9JeyZgOjRQH.ukwDGQtGxHsMJBJYOjOjyEAaIa','SUPER_ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO users(student_id,full_name_th,full_name_en,phone_number,email,password_hash,role) VALUES ('6810301035','จิรัฐพล วองวอน','Jirattapol Vingvorn','0876038181','6810301035@cdti.ac.th','$2b$12$0mKeKzwIJWFcFGOYUDZNmeIvTk1g8/HX4bl7btWlMabMS.rPVQIyy','STUDENT_RESIDENT') ON CONFLICT DO NOTHING;
INSERT INTO users(student_id,full_name_th,full_name_en,phone_number,email,password_hash,role) VALUES ('6510301001','วีระชัย สงวนกิตติพันธ์ุ','Weerachai Sa-ngounkittiphan','0985033392','6510301001@cdti.ac.th','$2b$12$/OSLzzC/FbcxYspBIvycOeBcjuyCyx1RliGU03yLzCblDH8aniGl6','STUDENT_RESIDENT') ON CONFLICT DO NOTHING;
INSERT INTO users(student_id,full_name_th,full_name_en,phone_number,email,password_hash,role) VALUES ('6810301028','หงษ์สกุล ศรีสวัสดิ์','Hongsakoun Sisavathdy','0820744167','6810301028@cdti.ac.th','$2b$12$hta.FuHxKoWCwffSjtJrG.Fjd5vrLS6RKJ2ncAejwt1Y0UFWJm1f.','STUDENT_RESIDENT') ON CONFLICT DO NOTHING;
INSERT INTO users(student_id,full_name_th,full_name_en,phone_number,email,password_hash,role) VALUES ('6810301010','พิภู สรศิริ','phiphu Sornsiri','0957208983','6810301010@cdti.ac.th','$2b$12$xZyetxSTa5PfeyWtobZyy.vAe2TnRoEv8nb6H5tp4FkCqp402ma3i','STUDENT_RESIDENT') ON CONFLICT DO NOTHING;
INSERT INTO users(student_id,full_name_th,full_name_en,phone_number,email,password_hash,role) VALUES ('6810301026','ธนพล แซ่เฉิน','Thanapol Saechern','0655039502','6810301026@cdti.ac.th','$2b$12$iHssJqevdW2Z7hDTQS5Te.F96xja98eadB4cKxwfN93EgAvXKZxEe','STUDENT_RESIDENT') ON CONFLICT DO NOTHING;
INSERT INTO room_types(id,name,bed_type,base_rent,deposit_amount,advance_payment,area_sqm,description,amenities) VALUES
 (1,'เตียงเดี่ยว','SINGLE',3000,3000,3000,24,'พื้นที่ส่วนตัวสำหรับการเรียนและพักผ่อน พร้อมเฟอร์นิเจอร์และห้องน้ำในตัว','["Wi-Fi","เครื่องปรับอากาศ","ห้องน้ำในตัว","โต๊ะอ่านหนังสือ"]'),
 (2,'เตียงคู่','TWIN',4000,4000,4000,32,'ห้องกว้างพร้อมเตียงแยกสองเตียง ตู้เสื้อผ้า และมุมอ่านหนังสือ','["Wi-Fi","เครื่องปรับอากาศ","ห้องน้ำในตัว","โต๊ะอ่านหนังสือ"]') ON CONFLICT DO NOTHING;
INSERT INTO rooms(id,room_number,floor,room_type_id,rent_rate) VALUES (1,'001',1,1,3000) ON CONFLICT DO NOTHING;
INSERT INTO room_images(room_id,asset_path,alt_text) VALUES (1,'/room-images/ชั้น1/เตียงเดี่ยว/เตียงเดี่ยว_001.png','ภาพประกอบห้อง 001 เตียงเดี่ยว') ON CONFLICT DO NOTHING;
INSERT INTO rooms(id,room_number,floor,room_type_id,rent_rate) VALUES (2,'002',1,1,3000) ON CONFLICT DO NOTHING;
INSERT INTO room_images(room_id,asset_path,alt_text) VALUES (2,'/room-images/ชั้น1/เตียงเดี่ยว/เตียงเดี่ยว_002.png','ภาพประกอบห้อง 002 เตียงเดี่ยว') ON CONFLICT DO NOTHING;
INSERT INTO leases(room_id,resident_id,start_date,end_date,deposit_paid) SELECT 2,id,'2026-08-01','2027-07-31',3000 FROM users WHERE student_id='6810301035' AND NOT EXISTS(SELECT 1 FROM leases WHERE room_id=2) AND NOT EXISTS(SELECT 1 FROM leases l WHERE l.resident_id=users.id) ON CONFLICT DO NOTHING;
INSERT INTO rooms(id,room_number,floor,room_type_id,rent_rate) VALUES (3,'003',1,1,3000) ON CONFLICT DO NOTHING;
INSERT INTO room_images(room_id,asset_path,alt_text) VALUES (3,'/room-images/ชั้น1/เตียงเดี่ยว/เตียงเดี่ยว_003.png','ภาพประกอบห้อง 003 เตียงเดี่ยว') ON CONFLICT DO NOTHING;
INSERT INTO rooms(id,room_number,floor,room_type_id,rent_rate) VALUES (4,'004',1,2,4000) ON CONFLICT DO NOTHING;
INSERT INTO room_images(room_id,asset_path,alt_text) VALUES (4,'/room-images/ชั้น1/เตียงคู่/เตียงคู่_004.png','ภาพประกอบห้อง 004 เตียงคู่') ON CONFLICT DO NOTHING;
INSERT INTO rooms(id,room_number,floor,room_type_id,rent_rate) VALUES (5,'005',1,2,4000) ON CONFLICT DO NOTHING;
INSERT INTO room_images(room_id,asset_path,alt_text) VALUES (5,'/room-images/ชั้น1/เตียงคู่/เตียงคู่_005.png','ภาพประกอบห้อง 005 เตียงคู่') ON CONFLICT DO NOTHING;
INSERT INTO leases(room_id,resident_id,start_date,end_date,deposit_paid) SELECT 5,id,'2026-08-01','2027-07-31',4000 FROM users WHERE student_id='6510301001' AND NOT EXISTS(SELECT 1 FROM leases WHERE room_id=5) AND NOT EXISTS(SELECT 1 FROM leases l WHERE l.resident_id=users.id) ON CONFLICT DO NOTHING;
INSERT INTO rooms(id,room_number,floor,room_type_id,rent_rate) VALUES (6,'006',1,2,4000) ON CONFLICT DO NOTHING;
INSERT INTO room_images(room_id,asset_path,alt_text) VALUES (6,'/room-images/ชั้น1/เตียงคู่/เตียงคู่_006.png','ภาพประกอบห้อง 006 เตียงคู่') ON CONFLICT DO NOTHING;
INSERT INTO rooms(id,room_number,floor,room_type_id,rent_rate) VALUES (7,'007',2,1,3000) ON CONFLICT DO NOTHING;
INSERT INTO room_images(room_id,asset_path,alt_text) VALUES (7,'/room-images/ชั้น2/เตียงเดี่ยว/เตียงเดี่ยว_007.png','ภาพประกอบห้อง 007 เตียงเดี่ยว') ON CONFLICT DO NOTHING;
INSERT INTO rooms(id,room_number,floor,room_type_id,rent_rate) VALUES (8,'008',2,1,3000) ON CONFLICT DO NOTHING;
INSERT INTO room_images(room_id,asset_path,alt_text) VALUES (8,'/room-images/ชั้น2/เตียงเดี่ยว/เตียงเดี่ยว_008.png','ภาพประกอบห้อง 008 เตียงเดี่ยว') ON CONFLICT DO NOTHING;
INSERT INTO leases(room_id,resident_id,start_date,end_date,deposit_paid) SELECT 8,id,'2026-08-01','2027-07-31',3000 FROM users WHERE student_id='6810301028' AND NOT EXISTS(SELECT 1 FROM leases WHERE room_id=8) AND NOT EXISTS(SELECT 1 FROM leases l WHERE l.resident_id=users.id) ON CONFLICT DO NOTHING;
INSERT INTO rooms(id,room_number,floor,room_type_id,rent_rate) VALUES (9,'009',2,1,3000) ON CONFLICT DO NOTHING;
INSERT INTO room_images(room_id,asset_path,alt_text) VALUES (9,'/room-images/ชั้น2/เตียงเดี่ยว/เตียงเดี่ยว_009.png','ภาพประกอบห้อง 009 เตียงเดี่ยว') ON CONFLICT DO NOTHING;
INSERT INTO rooms(id,room_number,floor,room_type_id,rent_rate) VALUES (10,'010',2,2,4000) ON CONFLICT DO NOTHING;
INSERT INTO room_images(room_id,asset_path,alt_text) VALUES (10,'/room-images/ชั้น2/เตียงคู่/เตียงคู่_010.png','ภาพประกอบห้อง 010 เตียงคู่') ON CONFLICT DO NOTHING;
INSERT INTO rooms(id,room_number,floor,room_type_id,rent_rate) VALUES (11,'011',2,2,4000) ON CONFLICT DO NOTHING;
INSERT INTO room_images(room_id,asset_path,alt_text) VALUES (11,'/room-images/ชั้น2/เตียงคู่/เตียงคู่_011.png','ภาพประกอบห้อง 011 เตียงคู่') ON CONFLICT DO NOTHING;
INSERT INTO leases(room_id,resident_id,start_date,end_date,deposit_paid) SELECT 11,id,'2026-08-01','2027-07-31',4000 FROM users WHERE student_id='6810301010' AND NOT EXISTS(SELECT 1 FROM leases WHERE room_id=11) AND NOT EXISTS(SELECT 1 FROM leases l WHERE l.resident_id=users.id) ON CONFLICT DO NOTHING;
INSERT INTO rooms(id,room_number,floor,room_type_id,rent_rate) VALUES (12,'012',2,2,4000) ON CONFLICT DO NOTHING;
INSERT INTO room_images(room_id,asset_path,alt_text) VALUES (12,'/room-images/ชั้น2/เตียงคู่/เตียงคู่_012.png','ภาพประกอบห้อง 012 เตียงคู่') ON CONFLICT DO NOTHING;
INSERT INTO rooms(id,room_number,floor,room_type_id,rent_rate) VALUES (13,'013',3,1,3000) ON CONFLICT DO NOTHING;
INSERT INTO room_images(room_id,asset_path,alt_text) VALUES (13,'/room-images/ชั้น3/เตียงเดี่ยว/เตียงเดี่ยว_013.png','ภาพประกอบห้อง 013 เตียงเดี่ยว') ON CONFLICT DO NOTHING;
INSERT INTO rooms(id,room_number,floor,room_type_id,rent_rate) VALUES (14,'014',3,1,3000) ON CONFLICT DO NOTHING;
INSERT INTO room_images(room_id,asset_path,alt_text) VALUES (14,'/room-images/ชั้น3/เตียงเดี่ยว/เตียงเดี่ยว_014.png','ภาพประกอบห้อง 014 เตียงเดี่ยว') ON CONFLICT DO NOTHING;
INSERT INTO leases(room_id,resident_id,start_date,end_date,deposit_paid) SELECT 14,id,'2026-08-01','2027-07-31',3000 FROM users WHERE student_id='6810301026' AND NOT EXISTS(SELECT 1 FROM leases WHERE room_id=14) AND NOT EXISTS(SELECT 1 FROM leases l WHERE l.resident_id=users.id) ON CONFLICT DO NOTHING;
INSERT INTO rooms(id,room_number,floor,room_type_id,rent_rate) VALUES (15,'015',3,1,3000) ON CONFLICT DO NOTHING;
INSERT INTO room_images(room_id,asset_path,alt_text) VALUES (15,'/room-images/ชั้น3/เตียงเดี่ยว/เตียงเดี่ยว_015.png','ภาพประกอบห้อง 015 เตียงเดี่ยว') ON CONFLICT DO NOTHING;
INSERT INTO rooms(id,room_number,floor,room_type_id,rent_rate) VALUES (16,'016',3,2,4000) ON CONFLICT DO NOTHING;
INSERT INTO room_images(room_id,asset_path,alt_text) VALUES (16,'/room-images/ชั้น3/เตียงคู่/เตียงคู่_016.png','ภาพประกอบห้อง 016 เตียงคู่') ON CONFLICT DO NOTHING;
INSERT INTO rooms(id,room_number,floor,room_type_id,rent_rate) VALUES (17,'017',3,2,4000) ON CONFLICT DO NOTHING;
INSERT INTO room_images(room_id,asset_path,alt_text) VALUES (17,'/room-images/ชั้น3/เตียงคู่/เตียงคู่_017.png','ภาพประกอบห้อง 017 เตียงคู่') ON CONFLICT DO NOTHING;
INSERT INTO rooms(id,room_number,floor,room_type_id,rent_rate) VALUES (18,'018',3,2,4000) ON CONFLICT DO NOTHING;
INSERT INTO room_images(room_id,asset_path,alt_text) VALUES (18,'/room-images/ชั้น3/เตียงคู่/เตียงคู่_018.png','ภาพประกอบห้อง 018 เตียงคู่') ON CONFLICT DO NOTHING;
INSERT INTO utility_rates(effective_date,water_rate_per_unit,electric_rate_per_unit) VALUES ('2026-08-01',18,8) ON CONFLICT DO NOTHING;
INSERT INTO meter_readings(room_id,billing_month,prev_water_unit,curr_water_unit,prev_electric_unit,curr_electric_unit) VALUES (2,'2026-09-01',100,106,500,560) ON CONFLICT DO NOTHING;
INSERT INTO invoices(invoice_number,room_id,resident_id,meter_reading_id,utility_rate_id,billing_cycle,rent_amount,water_amount,electric_amount,due_date)
 SELECT 'DF-202609-'||r.room_number,r.id,u.id,m.id,ur.id,'2026-09-01',r.rent_rate,(m.curr_water_unit-m.prev_water_unit)*ur.water_rate_per_unit,(m.curr_electric_unit-m.prev_electric_unit)*ur.electric_rate_per_unit,'2026-09-05'
 FROM rooms r JOIN users u ON u.student_id='6810301035' JOIN meter_readings m ON m.room_id=r.id AND m.billing_month='2026-09-01' JOIN utility_rates ur ON ur.effective_date='2026-08-01' WHERE r.id=2 ON CONFLICT DO NOTHING;
INSERT INTO meter_readings(room_id,billing_month,prev_water_unit,curr_water_unit,prev_electric_unit,curr_electric_unit) VALUES (5,'2026-09-01',100,107,500,570) ON CONFLICT DO NOTHING;
INSERT INTO invoices(invoice_number,room_id,resident_id,meter_reading_id,utility_rate_id,billing_cycle,rent_amount,water_amount,electric_amount,due_date)
 SELECT 'DF-202609-'||r.room_number,r.id,u.id,m.id,ur.id,'2026-09-01',r.rent_rate,(m.curr_water_unit-m.prev_water_unit)*ur.water_rate_per_unit,(m.curr_electric_unit-m.prev_electric_unit)*ur.electric_rate_per_unit,'2026-09-05'
 FROM rooms r JOIN users u ON u.student_id='6510301001' JOIN meter_readings m ON m.room_id=r.id AND m.billing_month='2026-09-01' JOIN utility_rates ur ON ur.effective_date='2026-08-01' WHERE r.id=5 ON CONFLICT DO NOTHING;
INSERT INTO meter_readings(room_id,billing_month,prev_water_unit,curr_water_unit,prev_electric_unit,curr_electric_unit) VALUES (8,'2026-09-01',100,108,500,580) ON CONFLICT DO NOTHING;
INSERT INTO invoices(invoice_number,room_id,resident_id,meter_reading_id,utility_rate_id,billing_cycle,rent_amount,water_amount,electric_amount,due_date)
 SELECT 'DF-202609-'||r.room_number,r.id,u.id,m.id,ur.id,'2026-09-01',r.rent_rate,(m.curr_water_unit-m.prev_water_unit)*ur.water_rate_per_unit,(m.curr_electric_unit-m.prev_electric_unit)*ur.electric_rate_per_unit,'2026-09-05'
 FROM rooms r JOIN users u ON u.student_id='6810301028' JOIN meter_readings m ON m.room_id=r.id AND m.billing_month='2026-09-01' JOIN utility_rates ur ON ur.effective_date='2026-08-01' WHERE r.id=8 ON CONFLICT DO NOTHING;
INSERT INTO meter_readings(room_id,billing_month,prev_water_unit,curr_water_unit,prev_electric_unit,curr_electric_unit) VALUES (11,'2026-09-01',100,109,500,590) ON CONFLICT DO NOTHING;
INSERT INTO invoices(invoice_number,room_id,resident_id,meter_reading_id,utility_rate_id,billing_cycle,rent_amount,water_amount,electric_amount,due_date)
 SELECT 'DF-202609-'||r.room_number,r.id,u.id,m.id,ur.id,'2026-09-01',r.rent_rate,(m.curr_water_unit-m.prev_water_unit)*ur.water_rate_per_unit,(m.curr_electric_unit-m.prev_electric_unit)*ur.electric_rate_per_unit,'2026-09-05'
 FROM rooms r JOIN users u ON u.student_id='6810301010' JOIN meter_readings m ON m.room_id=r.id AND m.billing_month='2026-09-01' JOIN utility_rates ur ON ur.effective_date='2026-08-01' WHERE r.id=11 ON CONFLICT DO NOTHING;
INSERT INTO meter_readings(room_id,billing_month,prev_water_unit,curr_water_unit,prev_electric_unit,curr_electric_unit) VALUES (14,'2026-09-01',100,110,500,600) ON CONFLICT DO NOTHING;
INSERT INTO invoices(invoice_number,room_id,resident_id,meter_reading_id,utility_rate_id,billing_cycle,rent_amount,water_amount,electric_amount,due_date)
 SELECT 'DF-202609-'||r.room_number,r.id,u.id,m.id,ur.id,'2026-09-01',r.rent_rate,(m.curr_water_unit-m.prev_water_unit)*ur.water_rate_per_unit,(m.curr_electric_unit-m.prev_electric_unit)*ur.electric_rate_per_unit,'2026-09-05'
 FROM rooms r JOIN users u ON u.student_id='6810301026' JOIN meter_readings m ON m.room_id=r.id AND m.billing_month='2026-09-01' JOIN utility_rates ur ON ur.effective_date='2026-08-01' WHERE r.id=14 ON CONFLICT DO NOTHING;
INSERT INTO staff_directory(name,role,shift_schedule,phone_number,is_emergency) VALUES ('สมชาย ใจดี','MANAGER','จันทร์ – เสาร์ 08:00 – 17:00','0811112233',false) ON CONFLICT DO NOTHING;
INSERT INTO staff_directory(name,role,shift_schedule,phone_number,is_emergency) VALUES ('สมศรี สะอาด','MAID','ทุกวัน 07:00 – 16:00','0822223344',false) ON CONFLICT DO NOTHING;
INSERT INTO staff_directory(name,role,shift_schedule,phone_number,is_emergency) VALUES ('มานะ ดูแล','SECURITY','ทุกวัน 07:00 – 19:00','0833334455',true) ON CONFLICT DO NOTHING;
INSERT INTO staff_directory(name,role,shift_schedule,phone_number,is_emergency) VALUES ('สันติ ปลอดภัย','SECURITY','ทุกวัน 19:00 – 07:00','0833334466',true) ON CONFLICT DO NOTHING;
INSERT INTO staff_directory(name,role,shift_schedule,phone_number,is_emergency) VALUES ('ประดิษฐ์ ช่างดี','TECHNICIAN','จันทร์ – เสาร์ 09:00 – 18:00','0899998877',false) ON CONFLICT DO NOTHING;
INSERT INTO dorm_regulations(category,rule_title,rule_content,penalty_details) VALUES ('QUIET','ความสงบเรียบร้อยและเสียงดัง','Quiet Hours 22:00 น. – 07:00 น. ห้ามจัดปาร์ตี้หรือเปิดเพลงเสียงดัง','ตักเตือนเกิน 2 ครั้ง ปรับครั้งละ 500 บาท') ON CONFLICT DO NOTHING;
INSERT INTO dorm_regulations(category,rule_title,rule_content,penalty_details) VALUES ('WASTE','การทิ้งขยะและความสะอาด','ห้ามวางถุงขยะหน้าห้องพักเด็ดขาด มัดปากถุงทิ้งที่ห้องขยะชั้น 1 คัดแยกขยะรีไซเคิลและขยะเปียก','กรุณาปฏิบัติตามจุดคัดแยกขยะ') ON CONFLICT DO NOTHING;
INSERT INTO dorm_regulations(category,rule_title,rule_content,penalty_details) VALUES ('SAFETY','ข้อห้ามด้านความปลอดภัยและสัตว์เลี้ยง','ห้ามสูบบุหรี่และบุหรี่ไฟฟ้าทุกกรณี ไม่อนุญาตให้เลี้ยงสัตว์ ห้ามใช้เตาแก๊ส อนุญาตเตาไฟฟ้าและไมโครเวฟ','สูบบุหรี่หรือบุหรี่ไฟฟ้า ปรับ 2,000 บาท') ON CONFLICT DO NOTHING;
INSERT INTO dorm_regulations(category,rule_title,rule_content,penalty_details) VALUES ('ACCESS','การเข้า–ออก และผู้มาติดต่อ','ประตูคีย์การ์ดสแกน ผู้มาติดต่อแลกบัตรกับ รปภ. ห้ามผู้มาติดต่อค้างคืนเกิน 23:00 น. ที่จอดรถห้องละ 1 คัน','ผู้มาติดต่อออกจากหอพักก่อน 23:00 น.') ON CONFLICT DO NOTHING;
INSERT INTO dorm_regulations(category,rule_title,rule_content,penalty_details) VALUES ('BILLING','การชำระเงินและค่าน้ำค่าไฟ','ชำระวันที่ 1 – 5 ทุกเดือน ค้างชำระเกินวันที่ 10 ระงับคีย์การ์ดและตัดกระแสไฟฟ้าชั่วคราว','ปรับล่าช้าวันละ 100 บาท') ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('room_types','id'),COALESCE((SELECT max(id) FROM room_types),1));
SELECT setval(pg_get_serial_sequence('rooms','id'),COALESCE((SELECT max(id) FROM rooms),1));
SELECT setval(pg_get_serial_sequence('utility_rates','id'),COALESCE((SELECT max(id) FROM utility_rates),1));
SELECT setval(pg_get_serial_sequence('meter_readings','id'),COALESCE((SELECT max(id) FROM meter_readings),1));
SELECT setval(pg_get_serial_sequence('staff_directory','id'),COALESCE((SELECT max(id) FROM staff_directory),1));
SELECT setval(pg_get_serial_sequence('dorm_regulations','id'),COALESCE((SELECT max(id) FROM dorm_regulations),1));
COMMIT;

